("Afghanistan"),
("Albania"),
("Algeria"),
("Andorra"),
("Angola"),
("Antigua and Barbuda"),
("Argentina"),
("Armenia"),
("Australia"),
("Austria"),
("Azerbaijan"),
("Bahamas"),
("Bahrain"),
("Bangladesh"),
("Barbados"),
("Belarus"),
("Belgium"),
("Belize"),
("Benin"),
("Bhutan"),
("Bolivia (Plurinational State of)"),
("Bosnia and Herzegovina"),
("Botswana"),
("Brazil"),
("Brunei Darussalam"),
("Bulgaria"),
("Burkina Faso"),
("Burundi"),
("Cabo Verde"),
("Cambodia"),
("Cameroon"),
("Canada"),
("Central African Republic"),
("Chad"),
("Chile"),
("China"),
("Colombia"),
("Comoros"),
("Congo"),
("Congo (Democratic Republic of the)"),
("Costa Rica"),
("Croatia"),
("Cuba"),
("Cyprus")